batch_size: 16
checkpoint_freq: 1000
data_aug_max_rotate: 0.1
data_aug_tps_cntl_pts: 4
data_aug_tps_variance: 0.05
data_aug_type: null
dataset_1: first_image
dataset_2: second_image
dataset_randomize: false
dataset_test_len: 1464
dataset_train_len: 71729
epochs: 24
model_in_channels: 3
model_keypoints: 10
model_type: F
model_z_channels: 64
opt_level: O2
